# Generated by Django 4.2.4 on 2023-09-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingreport',
            name='player_name',
            field=models.CharField(max_length=255),
        ),
    ]
